### ISSUE TITLE
Encountered an issue when running the latest 'stacked deep autoencoder' code.

### ISSUE THREAD

**Issue by yzsatgithub** [blackecho/Deep-Learning-TensorFlow#10]
I'm on commit 365fe44.  After running the command in the document, the stacked deep autoencoder stopped unexpectedly.
commands:
```
python command_line/run_stacked_autoencoder_unsupervised.py --dae_layers 512,256,128 --dae_batch_size 25 --dae_num_epochs 5 --verbose 1 --dae_corr_type masking --dae_corr_frac 0.0 --finetune_learning_rate 0.0001 --finetune_num_epochs 25 --finetune_opt gradient_descent --finetune_learning_rate 0.05 --dae_enc_act_func sigmoid --dae_dec_act_func sigmoid --dae_loss_func cross_entropy --finetune_enc_act_func tanh --finetune_dec_act_func sigmoid --finetune_loss_func cross_entropy --dropout 0.7
```

tracebacks:
```
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
Traceback (most recent call last):
  File "command_line/run_stacked_autoencoder_unsupervised.py", line 178, in <module>
    encoded_X, encoded_vX = sdae.pretrain(trX, vlX)
  File "./yadlt/models/autoencoder_models/stacked_deep_autoencoder.py", line 106, in pretrain
    next_train, next_valid = self._pretrain_autoencoder_and_gen_feed(autoenc, next_train, next_valid)
  File "./yadlt/models/autoencoder_models/stacked_deep_autoencoder.py", line 123, in _pretrain_autoencoder_and_gen_feed
    autoenc.fit(train_set, validation_set)
  File "./yadlt/models/autoencoder_models/denoising_autoencoder.py", line 67, in fit
    self.tf_saver.save(self.tf_session, self.model_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 827, in __exit__
    context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3215, in get_controller
    assert self.stack[-1] is default
IndexError: list index out of range
```

**Comment by blackecho** [comment]
The latest commit should have solved it. Please let me know if it works now, and thanks for pointing out the issue

**Comment by yzsatgithub** [comment]
Thank you. It works fine now.

**Comment by blackecho** [comment]
Great :)
