### ISSUE TITLE
Issue pretraining without validation set

### ISSUE THREAD

**Issue by Jakobovski** [blackecho/Deep-Learning-TensorFlow#14]
When trying to pretrain a `DeepAutoencoder` without a `validation_set` I get the following error:

`Traceback (most recent call last):
  File "multimodal-mnist/mnist_autoencoder.py", line 34, in <module>
    output = encoder.pretrain(train_x)
  File "/Users/Jackson/development/ai_experiments/venv/lib/python2.7/site-packages/yadlt/models/rbm_models/deep_autoencoder.py", line 109, in pretrain
    self.rbm_graphs[l])
  File "/Users/Jackson/development/ai_experiments/venv/lib/python2.7/site-packages/yadlt/models/rbm_models/deep_autoencoder.py", line 131, in _pretrain_rbm_and_gen_feed
    next_valid = rbm.transform(validation_set, graph=graph)
  File "/Users/Jackson/development/ai_experiments/venv/lib/python2.7/site-packages/yadlt/models/rbm_models/rbm.py", line 252, in transform
    encoded_data = self.sample_hidden_from_visible(data)[0].eval()
  File "/Users/Jackson/development/ai_experiments/venv/lib/python2.7/site-packages/yadlt/models/rbm_models/rbm.py", line 190, in sample_hidden_from_visible
    hprobs = tf.nn.sigmoid(tf.matmul(visible, self.W) + self.bh_)
  File "/Users/Jackson/development/ai_experiments/venv/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1023, in matmul
    a = ops.convert_to_tensor(a, name="a")
  File "/Users/Jackson/development/ai_experiments/venv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/Jackson/development/ai_experiments/venv/lib/python2.7/site-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/Jackson/development/ai_experiments/venv/lib/python2.7/site-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/Users/Jackson/development/ai_experiments/venv/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 325, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.`

**Comment by blackecho** [comment]
There was a missing check for None validation_set, the latest commit solved this issue. Thanks!

**Comment by Jakobovski** [comment]
👍
