### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'SerializeToString'   -- Version problems

### ISSUE THREAD

**Issue by yzsatgithub** [blackecho/Deep-Learning-TensorFlow#2]
Hi, backecho.    I got these tracebacks when running 
```
python command_line/run_stacked_autoencoder_unsupervised.py --layers 512,256,128 --batch_size 25 --num_epochs 5 --verbose 1 --corr_type masking --corr_frac 0.0 --finetune_learning_rate 0.001 --finetune_num_epochs 25 --opt gradient_descent --learning_rate 0.05 --enc_act_func sigmoid --dec_act_func sigmoid --loss_func cross_entropy --finetune_act_func tanh --dropout 0.7
```
I googled it and found this is a problem concerning the version of tensorflow. I am using r0.7.1 but the attribute `SerializeToString` seems to be in r0.8.   
Is there any other way to solve this problem apart from upgrading tensorflow?
```
Traceback (most recent call last):
  File "command_line/run_stacked_autoencoder_unsupervised.py", line 178, in <module>
    encoded_X, encoded_vX = sdae.pretrain(trX, vlX)
  File "./models/autoencoder_models/stacked_deep_autoencoder.py", line 132, in pretrain
    next_train, next_valid = self._pretrain_autoencoder_and_gen_feed(autoenc, next_train, next_valid)
  File "./models/autoencoder_models/stacked_deep_autoencoder.py", line 149, in _pretrain_autoencoder_and_gen_feed
    autoenc.fit(train_set, validation_set)
  File "./models/autoencoder_models/denoising_autoencoder.py", line 90, in fit
    self._initialize_tf_utilities_and_ops(restore_previous_model)
  File "./models/autoencoder_models/denoising_autoencoder.py", line 109, in _initialize_tf_utilities_and_ops
    self.tf_summary_writer = tf.train.SummaryWriter(self.tf_summary_dir, self.tf_session.graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/summary_io.py", line 104, in __init__
    self.add_graph(graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/summary_io.py", line 168, in add_graph
    graph_bytes = graph_def.SerializeToString()
AttributeError: 'Graph' object has no attribute 'SerializeToString'

```

**Comment by blackecho** [comment]
I also had the same problem. This is the [issue](https://github.com/tensorflow/tensorflow/issues/1690) in the tensorflow repository. They suggest to always upgrade to the latest version at least until 1.0 version. With 0.8 it works well.

**Comment by yzsatgithub** [comment]
@blackecho  haha alright. I'll keep that in mind. thx
