### ISSUE TITLE
Error when running run_deep_autoencoder.py

### ISSUE THREAD

**Issue by WillieMaddox** [blackecho/Deep-Learning-TensorFlow#21]
I'm getting the following error when running run_deep_autoencoder.py.
```
Traceback (most recent call last):
  File "/home/maddoxw/git/Deep-Learning-TensorFlow/command_line/run_deep_autoencoder.py", line 149, in <module>
    noise=FLAGS.rbm_noise, stddev=FLAGS.rbm_stddev)
  File "/home/maddoxw/.local/lib/python2.7/site-packages/yadlt/models/rbm_models/deep_autoencoder.py", line 77, in __init__
    visible_unit_type=expanded_args['noise'][l],
TypeError: 'bool' object has no attribute '__getitem__'
```

One possible issue I found is in the run_deep_autoencoder.py file on line:
```
flags.DEFINE_boolean('rbm_noise', 'gauss', 'Type of noise. Default: "gauss".')
```
The types don't match.  I'm not sure if it should be boolean or string?

Thanks

**Comment by blackecho** [comment]
Yep you're right, it should be string. It should be fixed now, thanks!
