### ISSUE TITLE
Bug: ImportError: No module named model

### ISSUE THREAD

**Issue by WillieMaddox** [blackecho/Deep-Learning-TensorFlow#23]
When running:
```bash
python /home/maddoxw/git/Deep-Learning-TensorFlow/command_line/run_deep_autoencoder.py --dataset cifar10 --cifar_dir /media/maddoxw/EXTRA/CIFAR-10/cifar-10-batches-py/ --main_dir deep-autoencoder --model_name deeper-is-better --rbm_layers 8192,2048,512,256 --rbm_batch_size 128 --finetune_batch_size 128 --finetune_loss_func cross_entropy
```
I get the following error:
```python
Traceback (most recent call last):
  File "/home/maddoxw/git/Deep-Learning-TensorFlow/command_line/run_deep_autoencoder.py", line 7, in <module>
    from yadlt.models.rbm_models import deep_autoencoder
  File "/home/maddoxw/.local/lib/python2.7/site-packages/yadlt/models/rbm_models/deep_autoencoder.py", line 11, in <module>
    from yadlt.core.unsupervised_model import UnsupervisedModel
  File "/home/maddoxw/.local/lib/python2.7/site-packages/yadlt/core/unsupervised_model.py", line 9, in <module>
    import model
ImportError: No module named model
```

unsupervised_model.py should see model.py since it's in the same folder.  Not sure why it doesn't.

**Comment by aabhi1119** [comment]
Even I get the same error,  please help me to fix this


ImportError                               Traceback (most recent call last)
<ipython-input-11-227f3a8fc4f3> in <module>()
      9 ("")
     10 # Project imports
---> 11 from model import *

ImportError: No module named 'model'
