### ISSUE TITLE
zip argument  must support iteration

### ISSUE THREAD

**Issue by yzsatgithub** [blackecho/Deep-Learning-TensorFlow#3]
When running the command below on r0.8,  I encounter a problem with zip function.
``` bash
 python command_line/run_stacked_autoencoder_unsupervised.py --layers 512,256,128 --batch_size 25 --num_epochs 5 --verbose 1 --corr_type masking --corr_frac 0.0 --finetune_learning_rate 0.001 --finetune_num_epochs 25 --opt gradient_descent --learning_rate 0.05 --enc_act_func sigmoid --dec_act_func sigmoid --loss_func cross_entropy --finetune_act_func tanh --dropout 0.7
```

``` 
Traceback (most recent call last):
  File "command_line/run_stacked_autoencoder_unsupervised.py", line 178, in <module>
    encoded_X, encoded_vX = sdae.pretrain(trX, vlX)
  File "./models/autoencoder_models/stacked_deep_autoencoder.py", line 132, in pretrain
    next_train, next_valid = self._pretrain_autoencoder_and_gen_feed(autoenc, next_train, next_valid)
  File "./models/autoencoder_models/stacked_deep_autoencoder.py", line 149, in _pretrain_autoencoder_and_gen_feed
    autoenc.fit(train_set, validation_set)
  File "./models/autoencoder_models/denoising_autoencoder.py", line 91, in fit
    self._train_model(train_set, validation_set)
  File "./models/autoencoder_models/denoising_autoencoder.py", line 122, in _train_model
    self._run_train_step(train_set)
  File "./models/autoencoder_models/denoising_autoencoder.py", line 137, in _run_train_step
    shuff = zip(train_set, x_corrupted)
TypeError: zip argument #2 must support iteration

```

this happens when run `run_stacked_autoencoder_unsupervised.py` with these command line parameters:
```
 --corr_type masking 
```
which makes the function `masking_noise()` in `utilities` be called.
```
# models/autoencoder_models/denoising_autoencoder.py
 def _corrupt_input(self, data):

        """ Corrupt a fraction of 'data' according to the
        noise method of this autoencoder.
        :return: corrupted data
        """

        corruption_ratio = np.round(self.corr_frac * data.shape[1]).astype(np.int)

        if self.corr_type == 'none':
            return np.copy(data)

        if self.corr_frac > 0.0:
            if self.corr_type == 'masking':
                return utilities.masking_noise(data, self.tf_session, self.corr_frac)

            elif self.corr_type == 'salt_and_pepper':
                return utilities.salt_and_pepper_noise(data, corruption_ratio)

        return None

```
```
# utils/utilities.py
def masking_noise(data, sess, v): 

    """ Apply masking noise to data in X, in other words a fraction v of elements of X
    (chosen at random) is forced to zero.
    :param data: array_like, Input data
    :param sess: TensorFlow session
    :param v: fraction of elements to distort, float
    :return: transformed data
    """

    data_noise = data.copy()
    rand = tf.random_uniform(data.shape)
    data_noise[sess.run(tf.nn.relu(tf.sign(v - rand))).astype(np.bool)] = 0 
                                                                                                                                                                
    return data_noise

```

So I found 'where' the bug is, but cannot figure out 'what' is going wrong.  what should be done to fix this problem?

**Comment by blackecho** [comment]
I solved it with the latest commit. The problem was that when `corr_type` is not 'none' and corr_frac is 0.0, None was returned, instead of a copy of the data. Thanks for finding the bug!

**Comment by yzsatgithub** [comment]
@blackecho   Your welcome~  good project and a good learning material!  and I thank YOU
