### ISSUE TITLE
ValueError: Dimensions 128 and 512 are not compatible && Reconstruction loss at step 0: nan

### ISSUE THREAD

**Issue by yzsatgithub** [blackecho/Deep-Learning-TensorFlow#4]
When running
```bash
 python command_line/run_stacked_autoencoder_unsupervised.py --layers 512,256,128 --batch_size 25 --num_epochs 5 --verbose 1  --corr_frac 0.0 --finetune_learning_rate 0.001 --finetune_num_epochs 25 --opt gradient_descent --learning_rate 0.05 --enc_act_func sigmoid --dec_act_func sigmoid --loss_func cross_entropy --finetune_act_func tanh --dropout 0.7
```
, I got this:
```
Traceback (most recent call last):
  File "command_line/run_stacked_autoencoder_unsupervised.py", line 181, in <module>
    sdae.build_model(trX.shape[1], encodingw, encodingb)
  File "./models/autoencoder_models/stacked_deep_autoencoder.py", line 296, in build_model
    self.reconstruction = self._create_decoding_layers(next_train)
  File "./models/autoencoder_models/stacked_deep_autoencoder.py", line 415, in _create_decoding_layers
    y_act = tf.matmul(next_decode, dec_w) + dec_b
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1036, in matmul
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 911, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2156, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1612, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/common_shapes.py", line 89, in matmul_shape
    inner_a.assert_is_compatible_with(inner_b)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 98, in assert_is_compatible_with
    % (self, other))
ValueError: Dimensions 128 and 512 are not compatible
```

After debugging I found the problem lies in:
```python
# models/autoencoder_models/stacked_deep_autoencoder.py
def _create_decoding_layers(self, last_encode):

        """ Create the decoding layers for reconstruction finetuning.
        :param last_encode: output of the last encoding layer
        :return: output of the final encoding layer.
              """                                                                                                                                                                             

        next_decode = last_encode

        for l, layer in enumerate(reversed(self.layers)):

            with tf.name_scope("decode-{}".format(l)):

                # Create decoding variables
                dec_w = tf.Variable(tf.transpose(self.encoding_w_[l].initialized_value()))
                dec_b = tf.Variable(tf.constant(0.01, shape=[dec_w.get_shape().dims[1].value]))
                self.decoding_w.append(dec_w)
                self.decoding_b.append(dec_b)

                print dec_w.get_shape().dims[0], dec_w.get_shape().dims[1] 
                print next_decode.get_shape().dims[0], next_decode.get_shape().dims[1]  
                y_act = tf.matmul(next_decode, dec_w) + dec_b

                if self.finetune_act_func == 'sigmoid':
                    layer_y = tf.nn.sigmoid(y_act)

                elif self.finetune_act_func == 'tanh':
                    layer_y = tf.nn.tanh(y_act)

                elif self.finetune_act_func == 'relu':
                    layer_y = tf.nn.relu(y_act)

                else:
                    layer_y = None

                # the input to the next layer is the output of this layer
                next_decode = tf.nn.dropout(layer_y, self.keep_prob)

            self.layer_nodes.append(next_decode)

        return next_decode

```

``` python
dec_w = tf.Variable(tf.transpose(self.encoding_w_[l].initialized_value()))
```
should be 
``` python
dec_w = tf.Variable(tf.transpose(self.encoding_w_[len(self.layers) - l -1].initialized_value()))
```

Then I got _classical_ nan problem in finetuning stage:
```
Reconstruction loss at step 0: nan
Reconstruction loss at step 1: nan
Reconstruction loss at step 2: nan
Reconstruction loss at step 3: nan
Reconstruction loss at step 4: nan
Reconstruction loss at step 5: nan
...
```

Is it because I didn't update to the newest code?

**Comment by blackecho** [comment]
Yes, I solved the problem in creating_decoding_layers() a few hours ago, and the NaN problem a few minutes ago. Update to the latest version and let me know if it is working now.

**Comment by yzsatgithub** [comment]
@blackecho yes, it's working. Errors and nan do not exist anymore.  But , at finetuning stage, the reconstruction loss displayed is increasing
```
Reconstruction loss at step 0: 1.43778
Reconstruction loss at step 1: 1.74266
Reconstruction loss at step 2: 1.67003
Reconstruction loss at step 3: 1.84512
Reconstruction loss at step 4: 1.92234
Reconstruction loss at step 5: 1.88207
Reconstruction loss at step 6: 1.90813
Reconstruction loss at step 7: 1.9251
Reconstruction loss at step 8: 2.00119
Reconstruction loss at step 9: 1.93428
Reconstruction loss at step 10: 2.01266
Reconstruction loss at step 11: 2.08079
Reconstruction loss at step 12: 2.10622
Reconstruction loss at step 13: 2.13075
Reconstruction loss at step 14: 2.18324
Reconstruction loss at step 15: 2.23437
Reconstruction loss at step 16: 2.26408
Reconstruction loss at step 17: 2.28209
Reconstruction loss at step 18: 2.30097
Reconstruction loss at step 19: 2.31744
Reconstruction loss at step 20: 2.32059
```
Is this normal？

**Comment by blackecho** [comment]
Mmh, maybe the learning rate is too high. Try decreasing `--finetune_learning_rate` to 0.0001 or so, and you should see the loss decrease.

**Comment by yzsatgithub** [comment]
Bravo, that's the key. you're so experienced.  thanks a lot~
```
Reconstruction loss at step 0: 2.9553
Reconstruction loss at step 1: 1.95894
Reconstruction loss at step 2: 1.76505
Reconstruction loss at step 3: 1.64569
Reconstruction loss at step 4: 1.58786
Reconstruction loss at step 5: 1.56089
Reconstruction loss at step 6: 1.61964
Reconstruction loss at step 7: 1.56537
Reconstruction loss at step 8: 1.6059
Reconstruction loss at step 9: 1.74353
Reconstruction loss at step 10: 1.71068
Reconstruction loss at step 11: 1.66869
Reconstruction loss at step 12: 1.64077
Reconstruction loss at step 13: 1.65717
Reconstruction loss at step 14: 1.60748
Reconstruction loss at step 15: 1.65448
Reconstruction loss at step 16: 1.70568
Reconstruction loss at step 17: 1.65327
Reconstruction loss at step 18: 1.66329
Reconstruction loss at step 19: 1.64087
Reconstruction loss at step 20: 1.63948
Reconstruction loss at step 21: 1.608
Reconstruction loss at step 22: 1.62511
Reconstruction loss at step 23: 1.55487
Reconstruction loss at step 24: 1.52736
Test set reconstruction loss: 1.55126273632


```

**Comment by blackecho** [comment]
I'm glad it works fine now =)
