### ISSUE TITLE
Proble with different models!! 

### ISSUE THREAD

**Issue by h3kt0rz** [blackecho/Deep-Learning-TensorFlow#56]
Hi,
I am having problem in implementation of different models even in Example Usage!

for example==>python run_dbn.py --dataset mnist --main_dir dbn-models --model_name my-deeper-dbn  --verbose 1 --rbm_layers 512,256 --rbm_learning_rate 0.005 --rbm_num_epochs 15 --rbm_batch_size 25 --finetune_batch_size 25 --finetune_learning_rate 0.001 --finetune_num_epochs 10 --finetune_loss_func softmax_cross_entropy --finetune_dropout 0.7 --finetune_act_func relu

output:
Traceback (most recent call last):
  File "run_dbn.py", line 71, in <module>
    trX, trY, vlX, vlY, teX, teY = datasets.load_mnist_dataset(mode='supervised')
  File "/home/h3kt0rz/.local/lib/python3.5/site-packages/yadlt/utils/datasets.py", line 27, in load_mnist_dataset
    mnist = input_data.read_data_sets("MNIST_data/", one_hot=one_hot)
  File "/home/homayoon/h3kt0rz/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 235, in read_data_sets
    SOURCE_URL + TRAIN_IMAGES)
  File "/home/h3kt0rz/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 208, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "/home/h3kt0rz/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 165, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/h3kt0rz/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 190, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Please help me

**Comment by KapoorHitesh** [comment]
Probably your link is broken.. try changing DEFAULT_SOURCE_URL to  'http://yann.lecun.com/exdb/mnist/'
 in <tensorflow env> Lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py

**Comment by yashkumaratri** [comment]
Default source https://storage.googleapis.com/cvdf-datasets/mnist/ isn't working now.
Thanks @KapoorHitesh for the update
