### ISSUE TITLE
Some problems when running 'Deep Autoencoder' on both CIFAR10 and MNIST

### ISSUE THREAD

**Issue by yzsatgithub** [blackecho/Deep-Learning-TensorFlow#6]
After downloading and unzipping cifar10 dataset, I tried deep autoencoder with:
```
python command_line/run_deep_autoencoder.py --dataset cifar10 --cifar_dir /home/data/cifar-10-batches-py/ --main_dir deep-autoencoder --model_name deeper-is-better --layers 8192,2048,512,256
```
something goes wrong at the fifth step in 1st layer pretraining:
```
Training layer 1...

Validation cost at step 0: 137.183
Validation cost at step 1: 137.183
Validation cost at step 2: 137.183
Validation cost at step 3: 137.183
Validation cost at step 4: 137.183
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
Traceback (most recent call last):
  File "command_line/run_deep_autoencoder.py", line 121, in <module>
    srbm.pretrain(trX, vlX)
  File "./models/rbm_models/deep_autoencoder.py", line 111, in pretrain
    next_train, next_valid = self._pretrain_rbm_and_gen_feed(rboltz, next_train, next_valid)
  File "./models/rbm_models/deep_autoencoder.py", line 135, in _pretrain_rbm_and_gen_feed
    return rboltz.transform(train_set), rboltz.transform(validation_set)
  File "./models/rbm_models/rbm.py", line 260, in transform
    encoded_data = self.sample_hidden_from_visible(data)[0].eval()
  File "./models/rbm_models/rbm.py", line 201, in sample_hidden_from_visible
    hprobs = tf.nn.sigmoid(tf.matmul(visible, self.W) + self.bh_)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1036, in matmul
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 911, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 486, in apply_op
    _Attr(op_def, input_arg.type_attr))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 59, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: DataType uint8 for attr 'T' not in list of allowed values: float32, float64, int32, complex64
```

Then I tried MNIST with:
```
python command_line/run_deep_autoencoder.py --dataset mnist --main_dir deep-autoencoder --model_name deeper-is-better --layers 512,256 --verbose 1 --rbm_num_epochs 5 --rbm_batch_size 100
```
The pretraining process went fine:
```
Training layer 1...
Validation cost at step 0: 0.140783
Validation cost at step 1: 0.122195
Validation cost at step 2: 0.111817
Validation cost at step 3: 0.104732
Validation cost at step 4: 0.0994828

Training layer 2...
Validation cost at step 0: 0.162714
Validation cost at step 1: 0.13298
Validation cost at step 2: 0.117772
Validation cost at step 3: 0.108244
Validation cost at step 4: 0.101742
```
But at finetuning stage:
```
Start deep autoencoder finetuning...
Traceback (most recent call last):
  File "command_line/run_deep_autoencoder.py", line 127, in <module>
    srbm.build_model(trX.shape[1])
  File "./models/rbm_models/deep_autoencoder.py", line 203, in build_model
    encode_output = self._create_encoding_layers()
  File "./models/rbm_models/deep_autoencoder.py", line 245, in _create_encoding_layers
    hstates = utilities.sample_prob(hprobs, self.hrand[l])
  File "./utils/utilities.py", line 20, in sample_prob
    return tf.nn.relu(tf.sign(probs - rand))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 518, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1683, in sub
    return _op_def_lib.apply_op("Sub", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2156, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1612, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1390, in _BroadcastShape
    % (shape_x, shape_y))
ValueError: Incompatible shapes for broadcasting: (?, 512) and (?, 256)

```

Could you figure out what's wrong?

**Comment by blackecho** [comment]
Both these issues should be solved with the latest commit. Let me know if it works now.

**Comment by yzsatgithub** [comment]
@blackecho  
SORRY I was a little busy recently, should have replied earlier.
 glad you switched to os.path.join, i was about to mention that.   and i also added reconstruct() to commit .          mnist works fine but cifar10 didn't. u missed a small FLAG and i can fixed it by just adding one.

**Comment by blackecho** [comment]
If you mean the `save_layers_output` flag yes, it was missing. I added it with the latest commit.
What error does cifar10 give to you?

**Comment by yzsatgithub** [comment]
Yes I meant that. : - )    nothing more.
