### ISSUE TITLE
LSTM: the problem of data serialization.

### ISSUE THREAD

**Issue by rosefun** [blackecho/Deep-Learning-TensorFlow#74]
The input_data.shape is  (35200, 22).
The problem is as follows:

```
    train_perplexity = self._run_train_step(train_set, 'train')
  File "F:\DBN-rbm-classification\yadlt\models\recurrent\lstm.py", line 92, in _run_train_step
    data, self.batch_size, self.num_steps)):
  File "F:\DBN-rbm-classification\yadlt\utils\utilities.py", line 77, in seq_data_iterator
    data[i] = raw_data[batch_len * i:batch_len * (i + 1)]

ValueError: could not broadcast input array from shape (1760,52) into shape (1760)
```
In utilities.py:
```
def seq_data_iterator(raw_data, batch_size, num_steps):
    """Sequence data iterator.

    Taken from tensorflow/models/rnn/ptb/reader.py
    """
    raw_data = np.array(raw_data, dtype=np.int32)
    print('raw_data.shape',raw_data.shape)
    
    data_len = len(raw_data)
    print('data_len',data_len)
    
    batch_len = data_len // batch_size
    data = np.zeros([batch_size, batch_len], dtype=np.int32)
    
    for i in range(batch_size):
        data[i] = raw_data[batch_len * i:batch_len * (i + 1)]
        print('data i',data[i])
    epoch_size = (batch_len - 1) // num_steps

    if epoch_size == 0:
        raise ValueError("epoch_size == 0, decrease batch_size or num_steps")

    for i in range(epoch_size):
        x = data[:, i * num_steps: (i+1) * num_steps]
        y = data[:, i * num_steps + 1: (i+1) * num_steps + 1]
        print('x',x.shape)
        print('y',y.shape)
    yield (x, y)
```
I know the shape of my data is not matched the 'seq_data_iterator'.
What I try to do:
Change the shape of data,
```
data = np.zeros([batch_size, batch_len,len(raw_data[1])], dtype=np.int32)#
```

However, another problem occurs:
```
Traceback (most recent call last):
  File "F:\DBN-rbm-classification\cmd_line\recurrent/run_lstm.py", line 182, in <module>
    model.fit(trX, teX)
  File "F:\DBN-rbm-classification\yadlt\models\recurrent\lstm.py", line 68, in fit
    train_perplexity = self._run_train_step(train_set, 'train')
  File "F:\DBN-rbm-classification\yadlt\models\recurrent\lstm.py", line 97, in _run_train_step
    self._init_state: state})

  File "D:\anaconda3.5\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "D:\anaconda3.5\lib\site-packages\tensorflow\python\client\session.py", line 1116, in _run
    str(subfeed_t.get_shape())))

ValueError: Cannot feed value of shape (20, 35, 52) for Tensor 'model/Placeholder:0', which has shape '(20, 35)'
```
So,I change the shape of input_data:
```  
def _create_placeholders(self):
        """Create the computational graph's placeholders."""
        self.input_data = tf.placeholder(
            tf.int32, [self.batch_size, self.num_steps,len(self.raw.shape[1])])
        self.input_labels = tf.placeholder(
            tf.int32, [self.batch_size, self.num_steps,len(self.raw.shape[1])])
```
And, the new error is:
```
  File "F:\DBN-rbm-classification\cmd_line\recurrent/run_lstm.py", line 182, in <module>
    model.fit(trX, teX)
  File "F:\DBN-rbm-classification\yadlt\models\recurrent\lstm.py", line 59, in fit
    self.build_model()
  File "F:\DBN-rbm-classification\yadlt\models\recurrent\lstm.py", line 114, in build_model
    self._create_rnn_architecture()
  File "F:\DBN-rbm-classification\yadlt\models\recurrent\lstm.py", line 149, in _create_rnn_architecture
    outputs, state = tf.contrib.rnn.static_rnn(self.cell, self.inputs, initial_state=self._init_state)

ValueError: Input 0 of layer lstm_cell_1 is incompatible with the layer: expected ndim=2, found ndim=3. Full shape received: [20, 52, 200]
```
Anybody knows how to solve it?

**Comment by imen19** [comment]
Hello, I came across the same issue , did you find any solution?
